name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            python-version: "3.10"
          - os: ubuntu-22.04
            python-version: "3.11"
          - os: ubuntu-22.04
            python-version: "3.12"
          - os: ubuntu-22.04
            python-version: "3.13"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          auto-update-conda: false
          channels: andrsd,defaults

      - name: Checkout source
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          conda install \
            cmake \
            make \
            cxx-compiler \
            fmt=11.* \
            hdf5 \
            eigen \
            gtest \
            pybind11 \
            flake8 \
            pytest \
            lcov

      - name: Configure
        run: |
          cmake -S . -B ${{ github.workspace }}/build \
            -DGCOV_PATH=`which x86_64-conda-linux-gnu-gcov` \
            -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_CXX_FLAGS_DEBUG="-g -Wall -Werror" \
            -DFPROPS_BUILD_TESTS=YES \
            -DFPROPS_WITH_PYTHON=YES \
            -DFPROPS_CODE_COVERAGE=YES

      - name: Build
        run: cmake --build ${{ github.workspace }}/build

      - name: Install
        run: cmake --install ${{ github.workspace }}/build

      - name: Run unit tests
        run: |
          ${{ github.workspace }}/build/test/fprops-test \
            --gtest_output=xml:${{ github.workspace }}/build/gtest-results.xml

      - name: Test summary
        uses: test-summary/action@v2
        if: always()
        with:
          paths: ${{ github.workspace }}/build/gtest-results.xml
          show: "fail, skip"

      - name: Upload test results to codecov.io
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ${{ github.workspace }}/build/gtest-results.xml
          name: ${{ matrix.os }}-${{ matrix.python-version }}

      - name: Run python tests
        run: |
          pytest ${{ github.workspace }}/python/tests

      - name: Generate code coverage
        if: startsWith(matrix.os, 'ubuntu')
        run: cmake --build ${{ github.workspace }}/build --target coverage

      - name: Upload coverage artifact
        if: startsWith(matrix.os, 'ubuntu')
        uses: actions/upload-artifact@v7
        with:
          name: coverage-${{ matrix.os }}-${{ matrix.python-version }}
          path: ${{ github.workspace }}/build/coverage.info

  upload-to-codecov:
    needs: [build]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Download artifacts
        uses: actions/download-artifact@v8

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
