name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linux-clang:
    runs-on: ubuntu-22.04
    name: ubuntu-clang
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt install libfmt-dev
      - name: Configure
        run: |
          cmake -S . -B ${{ github.workspace }}/build \
            -DFPROPS_BUILD_TESTS=YES
      - name: Build
        run: make -C ${{ github.workspace }}/build
      - name: Run tests
        run: make -C ${{ github.workspace }}/build test ARGS='-V'

  linux-gcc:
    runs-on: ubuntu-22.04
    name: ubuntu-gcc
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt install libfmt-dev
      - name: Configure
        run: |
          cmake -S . -B ${{ github.workspace }}/build \
            -DFPROPS_BUILD_TESTS=YES
      - name: Build
        run: make -C ${{ github.workspace }}/build
      - name: Run tests
        run: make -C ${{ github.workspace }}/build test ARGS='-V'

  macosx-clang:
    runs-on: macos-10.15
    name: macosx-clang
    env:
      SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Install dependencies
        run: brew install cmake llvm@12 fmt
      - name: Configure
        run: |
          cmake -S . -B ${{ github.workspace }}/build \
            -DFPROPS_BUILD_TESTS=YES
      - name: Build
        run: make -C ${{ github.workspace }}/build
      - name: Run tests
        run: make -C ${{ github.workspace }}/build test ARGS='-V'
