name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-11]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Install dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update -qq
          sudo apt install libfmt-dev python3-pybind11
      - name: Install dependencies
        if: startsWith(matrix.os, 'macos')
        run: brew install cmake llvm@12 fmt pybind11
      - name: Install python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install flake8 pytest
      - name: Configure
        run: |
          cmake -S . -B ${{ github.workspace }}/build \
            -DFPROPS_BUILD_TESTS=YES
      - name: Build
        run: make -C ${{ github.workspace }}/build
      - name: Run tests
        run: make -C ${{ github.workspace }}/build test ARGS='-V'
