name: github-pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          channels: conda-forge,default
          channel-priority: struct

      - name: Install dependencies
        run: |
          conda install \
            doxygen \
            sphinx \
            sphinx_rtd_theme \
            sphinxcontrib-bibtex \
            breathe \
            sphinx-tabs \
            coolprop \
            pybind11 \
            pytest \
            hdf5 \
            eigen \
            fmt

      - name: Build doco
        run: |
          cmake -S . -B ${{ github.workspace }}/build \
            -DCMAKE_PREFIX_PATH=$CONDA_PREFIX
          make -C ${{ github.workspace }}/build all
          make -C ${{ github.workspace }}/build doc

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{ github.workspace }}/build/docs/html
